#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    Jul 12, 2024 03:52:42 PM PDT  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import adduserui
import adduserlib

_debug = True # False to eliminate debug printing from callback functions.

def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = adduserui.Toplevel1(_top1)
    root.mainloop()

def AddUserStart(addusername):
    import adduserlib
   
    adduserlib.adduser(addusername)
    

if __name__ == '__main__':
    adduserui.start_up()




